version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=disenio
      - MYSQL_ROOT_PASSWORD=disenio
    ports:
      - '3306:3306'
volumes:
  db:
    driver: local